[package]
name = "axum-reverse-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.5", features = ["full"] }
http-body-util = "0.1"
bytes = "1.0"
tracing = "0.1"
serde_json = "1.0"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
tracing-subscriber = "0.3"
criterion = { version = "0.5", features = ["async_tokio", "html_reports"] }

[[bench]]
name = "proxy_bench"
harness = false
