[package]
name = "rproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
bytes = "1.9.0"
http-body-util = "0.1.2"
hyper = { version = "1.5.2", features = ["client", "http1"] }
hyper-util = { version = "0.1.10", features = ["client", "client-legacy", "http1"] }
tokio = { version = "1.42.0", features = ["full"] }
tower = "0.5.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = "1.0.134"
tokio-test = "0.4.4"
