name: Benchmark

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GKE_CLUSTER: axum-proxy-benchmarks
  GKE_ZONE: us-central1-a
  PROJECT_ID: axum-proxy-benchmarks

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib seaborn pandas jq

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Run benchmarks
      run: |
        chmod +x benchmarks/run-comprehensive-benchmark.sh
        chmod +x benchmarks/scripts/generate_plots.py
        ./benchmarks/run-comprehensive-benchmark.sh

    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: |
          benchmarks/results/
          benchmarks/plots/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./benchmarks/results
        keep_files: true 