name: Benchmark

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GKE_CLUSTER: axum-proxy-benchmarks
  GKE_ZONE: us-central1-a
  PROJECT_ID: axum-proxy-benchmarks

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib seaborn pandas jq

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Run benchmarks
      run: |
        chmod +x benchmarks/deploy.sh
        chmod +x benchmarks/run-comprehensive-benchmark.sh
        ./benchmarks/deploy.sh
        ./benchmarks/run-comprehensive-benchmark.sh

    - name: Generate plots
      run: python generate_plots.py

    - name: Prepare benchmark results
      run: |
        mkdir -p benchmark_results
        cp -r benchmarks/results/* benchmark_results/
        cp generate_plots.py benchmark_results/

    - name: Deploy to benchmark-results branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: benchmark-results
        publish_dir: ./benchmark_results
        keep_files: false
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Update benchmark results [skip ci]' 